# Commands to start on workspace startup
tasks:
  - init: |
      cd workshop
      mvn clean install test -DskipTests=true
      clear
    command: echo 'Ready to test!'

vscode:
  extensions:
    - vscjava.vscode-java-test
